# Generated by Django 3.2.5 on 2021-10-20 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Área de atuação',
                'verbose_name_plural': 'Áreas de atuação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cultura',
                'verbose_name_plural': 'Culturas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MaturidadeAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Maturidade acadêmica',
                'verbose_name_plural': 'Maturidades acadêmica',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MaturidadeProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Maturidade profissional',
                'verbose_name_plural': 'Maturidades profissionais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Prêmio',
                'verbose_name_plural': 'Prêmios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('linkedin_url', models.CharField(max_length=255)),
                ('areas_atuacao', models.ManyToManyField(to='core.AreaAtuacao')),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cultura')),
                ('habilidades', models.ManyToManyField(to='core.Habilidade')),
                ('maturidade_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maturidadeacademica')),
                ('maturidade_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maturidadeprofissional')),
                ('premios', models.ManyToManyField(to='core.Premio')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.areaatuacao')),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cultura')),
            ],
            options={
                'verbose_name': 'Startup',
                'verbose_name_plural': 'Startups',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('areas_atuacao', models.ManyToManyField(to='core.AreaAtuacao')),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cultura')),
                ('habilidades', models.ManyToManyField(to='core.Habilidade')),
                ('maturidade_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maturidadeacademica')),
                ('maturidade_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maturidadeprofissional')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissional')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.startup')),
            ],
        ),
        migrations.CreateModel(
            name='RecomendacaoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('recomendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissional')),
                ('recomendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissional_recomendador', to='core.profissional')),
            ],
            options={
                'verbose_name': 'Recomendação profissional',
                'verbose_name_plural': 'Recomendações profissionais',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.startup')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='profissional',
            name='projetos',
            field=models.ManyToManyField(to='core.Projeto'),
        ),
    ]
