# Generated by Django 3.2.5 on 2021-12-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endocos',
            options={'verbose_name': 'Endoço', 'verbose_name_plural': 'Endoços'},
        ),
    ]
