# Generated by Django 3.2.5 on 2021-10-27 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaga',
            options={'ordering': ['titulo'], 'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
        migrations.AddField(
            model_name='profissional',
            name='startups',
            field=models.ManyToManyField(blank=True, to='core.Startup'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cultura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culturas', to='core.cultura'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='maturidade_profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maturidades_profissionais', to='core.maturidadeprofissional'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='premios',
            field=models.ManyToManyField(blank=True, to='core.Premio'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='projetos',
            field=models.ManyToManyField(blank=True, to='core.Projeto'),
        ),
    ]
