# Generated by Django 3.2.5 on 2021-07-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('areas_atuacao', models.ManyToManyField(to='core.AreaAtuacao')),
                ('habilidades', models.ManyToManyField(to='core.Habilidade')),
                ('maturidade_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maturidadeacademica')),
                ('maturidade_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.maturidadeprofissional')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.startup')),
            ],
        ),
    ]
