# Generated by Django 3.2.5 on 2021-10-27 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211026_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='cultura',
        ),
    ]
