# Generated by Django 3.2.5 on 2021-12-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_endocos_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endocos',
            new_name='Endossos',
        ),
        migrations.AlterModelOptions(
            name='endossos',
            options={'verbose_name': 'Endosso', 'verbose_name_plural': 'Endossos'},
        ),
    ]
