# Generated by Django 3.2.5 on 2021-11-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_premios_recomendacaoprofissional_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacaoprofissional',
            name='habilidades',
            field=models.ManyToManyField(to='core.Habilidade'),
        ),
    ]
