# Generated by Django 3.2.5 on 2021-11-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_recomendacaoprofissional_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='core.Habilidade'),
        ),
    ]
