# Generated by Django 3.2.5 on 2021-11-02 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profissional_habilidades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecomendacaoProfissional',
            new_name='RecomendacaoHabilidades',
        ),
        migrations.AlterModelOptions(
            name='recomendacaohabilidades',
            options={'verbose_name': 'Recomendação de habilidade', 'verbose_name_plural': 'Recomendações de habilidades'},
        ),
    ]
