# Generated by Django 3.2.5 on 2021-11-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_nps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nps',
            options={'verbose_name': 'Nps', 'verbose_name_plural': 'Nps'},
        ),
    ]
