# Generated by Django 3.2.5 on 2021-11-17 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_nps_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nps',
            name='nota',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
