# Generated by Django 3.2.5 on 2021-11-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_nps_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nps',
            options={'verbose_name': 'Nota', 'verbose_name_plural': 'Nota'},
        ),
    ]
