# Generated by Django 3.2.5 on 2021-11-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_nps_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='area',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='profissional',
        ),
    ]
