# Generated by Django 3.2.5 on 2021-12-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20211124_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='nps',
            name='sugestao',
            field=models.CharField(default='', max_length=500),
        ),
    ]
