# Generated by Django 3.2.5 on 2021-12-12 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_nps_sugestao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendaria', models.BooleanField(null=True)),
                ('sugestao', models.TextField(null=True)),
                ('recrutador', models.CharField(max_length=255, null=True)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(null=True)),
                ('contrataria', models.BooleanField(null=True)),
                ('posicao_lista', models.IntegerField(null=True)),
                ('experimento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.experimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.profissional')),
            ],
        ),
    ]
