# Generated by Django 3.2.5 on 2021-12-12 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_experimento_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimento',
            name='vaga',
        ),
        migrations.AddField(
            model_name='notas',
            name='vaga',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='core.vaga'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experimento',
            name='recomendaria',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimento',
            name='recrutador',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experimento',
            name='sugestao',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='contrataria',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='nota',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='posicao_lista',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
