#drop database mana;
#create database mana;

USE mana;
INSERT INTO core_areaatuacao (nome) VALUES ('Administração agrícola');
INSERT INTO core_areaatuacao (nome) VALUES ('Administração de serviços');
INSERT INTO core_areaatuacao (nome) VALUES ('Administração governamental');
INSERT INTO core_areaatuacao (nome) VALUES ('Agricultura');
INSERT INTO core_areaatuacao (nome) VALUES ('Alimentos e bebidas');
INSERT INTO core_areaatuacao (nome) VALUES ('Animação');
INSERT INTO core_areaatuacao (nome) VALUES ('Armazenagem');
INSERT INTO core_areaatuacao (nome) VALUES ('Arquitetura e planejamento');
INSERT INTO core_areaatuacao (nome) VALUES ('Arrecadação de recursos');
INSERT INTO core_areaatuacao (nome) VALUES ('Artes cênicas');
INSERT INTO core_areaatuacao (nome) VALUES ('Artes e artesanato');
INSERT INTO core_areaatuacao (nome) VALUES ('Atacado');
INSERT INTO core_areaatuacao (nome) VALUES ('Atendimento ao consumidor');
INSERT INTO core_areaatuacao (nome) VALUES ('Atendimento médico e hospitalar');
INSERT INTO core_areaatuacao (nome) VALUES ('Atendimento médico psiquiátrico');
INSERT INTO core_areaatuacao (nome) VALUES ('Atividades parlamentares');
INSERT INTO core_areaatuacao (nome) VALUES ('Automação industrial');
INSERT INTO core_areaatuacao (nome) VALUES ('Aviação e aeroespacial');
INSERT INTO core_areaatuacao (nome) VALUES ('Bancos');
INSERT INTO core_areaatuacao (nome) VALUES ('Bancos de investimento');
INSERT INTO core_areaatuacao (nome) VALUES ('Belas-artes');
INSERT INTO core_areaatuacao (nome) VALUES ('Bens de consumo');
INSERT INTO core_areaatuacao (nome) VALUES ('Bibliotecas');
INSERT INTO core_areaatuacao (nome) VALUES ('Biotecnologia');
INSERT INTO core_areaatuacao (nome) VALUES ('Capital de risco e participações privadas');
INSERT INTO core_areaatuacao (nome) VALUES ('Cinema e filmes');
INSERT INTO core_areaatuacao (nome) VALUES ('Composição e revisão de textos');
INSERT INTO core_areaatuacao (nome) VALUES ('Comércio e desenvolvimento internacional');
INSERT INTO core_areaatuacao (nome) VALUES ('Construção');
INSERT INTO core_areaatuacao (nome) VALUES ('Construção de ferrovia');
INSERT INTO core_areaatuacao (nome) VALUES ('Construção naval');
INSERT INTO core_areaatuacao (nome) VALUES ('Consultoria de gerenciamento');
INSERT INTO core_areaatuacao (nome) VALUES ('Contabilidade');
INSERT INTO core_areaatuacao (nome) VALUES ('Cosmética');
INSERT INTO core_areaatuacao (nome) VALUES ('Defesa e espaço');
INSERT INTO core_areaatuacao (nome) VALUES ('Desenvolvimento de programas');
INSERT INTO core_areaatuacao (nome) VALUES ('Design');
INSERT INTO core_areaatuacao (nome) VALUES ('Design gráfico');
INSERT INTO core_areaatuacao (nome) VALUES ('Dispositivos médicos');
INSERT INTO core_areaatuacao (nome) VALUES ('Editoração');
INSERT INTO core_areaatuacao (nome) VALUES ('Educação à distância');
INSERT INTO core_areaatuacao (nome) VALUES ('Embalagens e recipientes');
INSERT INTO core_areaatuacao (nome) VALUES ('Engenharia civil');
INSERT INTO core_areaatuacao (nome) VALUES ('Engenharia mecânica ou industrial');
INSERT INTO core_areaatuacao (nome) VALUES ('Ensino fundamental/médio');
INSERT INTO core_areaatuacao (nome) VALUES ('Ensino superior');
INSERT INTO core_areaatuacao (nome) VALUES ('Entrega de encomendas e fretes');
INSERT INTO core_areaatuacao (nome) VALUES ('Entretenimento');
INSERT INTO core_areaatuacao (nome) VALUES ('Esportes');
INSERT INTO core_areaatuacao (nome) VALUES ('Execução da lei');
INSERT INTO core_areaatuacao (nome) VALUES ('Filantropia');
INSERT INTO core_areaatuacao (nome) VALUES ('Fotografia');
INSERT INTO core_areaatuacao (nome) VALUES ('Gabinete presidencial');
INSERT INTO core_areaatuacao (nome) VALUES ('Games para celular');
INSERT INTO core_areaatuacao (nome) VALUES ('Gestão de investimentos');
INSERT INTO core_areaatuacao (nome) VALUES ('Gestão de organização sem fins lucrativos');
INSERT INTO core_areaatuacao (nome) VALUES ('Gestão educacional');
INSERT INTO core_areaatuacao (nome) VALUES ('Hardware');
INSERT INTO core_areaatuacao (nome) VALUES ('Hotelaria');
INSERT INTO core_areaatuacao (nome) VALUES ('Imobiliário');
INSERT INTO core_areaatuacao (nome) VALUES ('Importação e exportação');
INSERT INTO core_areaatuacao (nome) VALUES ('Impressão');
INSERT INTO core_areaatuacao (nome) VALUES ('Imóveis comerciais');
INSERT INTO core_areaatuacao (nome) VALUES ('Indústria automotiva');
INSERT INTO core_areaatuacao (nome) VALUES ('Indústria farmacêutica');
INSERT INTO core_areaatuacao (nome) VALUES ('Indústria química');
INSERT INTO core_areaatuacao (nome) VALUES ('Indústria têxtil');
INSERT INTO core_areaatuacao (nome) VALUES ('Instalações e serviços de recreação');
INSERT INTO core_areaatuacao (nome) VALUES ('Instituições religiosas');
INSERT INTO core_areaatuacao (nome) VALUES ('Internet');
INSERT INTO core_areaatuacao (nome) VALUES ('Jogos de azar');
INSERT INTO core_areaatuacao (nome) VALUES ('Jogos de computador');
INSERT INTO core_areaatuacao (nome) VALUES ('Jornais');
INSERT INTO core_areaatuacao (nome) VALUES ('Judiciário');
INSERT INTO core_areaatuacao (nome) VALUES ('Laticínios');
INSERT INTO core_areaatuacao (nome) VALUES ('Lazer, viagens e turismo');
INSERT INTO core_areaatuacao (nome) VALUES ('Linhas aéreas/Aviação');
INSERT INTO core_areaatuacao (nome) VALUES ('Logística e cadeia de suprimentos');
INSERT INTO core_areaatuacao (nome) VALUES ('Manufatura de eletroeletrônicos');
INSERT INTO core_areaatuacao (nome) VALUES ('Maquinário');
INSERT INTO core_areaatuacao (nome) VALUES ('Marketing e publicidade');
INSERT INTO core_areaatuacao (nome) VALUES ('Materiais de construção');
INSERT INTO core_areaatuacao (nome) VALUES ('Materiais esportivos');
INSERT INTO core_areaatuacao (nome) VALUES ('Medicina alternativa');
INSERT INTO core_areaatuacao (nome) VALUES ('Mercados de capital');
INSERT INTO core_areaatuacao (nome) VALUES ('Militar');
INSERT INTO core_areaatuacao (nome) VALUES ('Mineração e metais');
INSERT INTO core_areaatuacao (nome) VALUES ('Museus e instituições');
INSERT INTO core_areaatuacao (nome) VALUES ('Mídia de difusão');
INSERT INTO core_areaatuacao (nome) VALUES ('Mídia online');
INSERT INTO core_areaatuacao (nome) VALUES ('Móveis');
INSERT INTO core_areaatuacao (nome) VALUES ('Música');
INSERT INTO core_areaatuacao (nome) VALUES ('Nanotecnologia');
INSERT INTO core_areaatuacao (nome) VALUES ('Organização cívica e social');
INSERT INTO core_areaatuacao (nome) VALUES ('Organização política');
INSERT INTO core_areaatuacao (nome) VALUES ('Organizações de pesquisa e orientação');
INSERT INTO core_areaatuacao (nome) VALUES ('Papel e produtos florestais');
INSERT INTO core_areaatuacao (nome) VALUES ('Pesca');
INSERT INTO core_areaatuacao (nome) VALUES ('Pesquisa');
INSERT INTO core_areaatuacao (nome) VALUES ('Pesquisa de mercado');
INSERT INTO core_areaatuacao (nome) VALUES ('Petróleo e energia');
INSERT INTO core_areaatuacao (nome) VALUES ('Plástico');
INSERT INTO core_areaatuacao (nome) VALUES ('Política pública');
INSERT INTO core_areaatuacao (nome) VALUES ('Produtos alimentícios');
INSERT INTO core_areaatuacao (nome) VALUES ('Produtos de luxo e joias');
INSERT INTO core_areaatuacao (nome) VALUES ('Produtos eletrônicos');
INSERT INTO core_areaatuacao (nome) VALUES ('Produção de mídia');
INSERT INTO core_areaatuacao (nome) VALUES ('Prática jurídica');
INSERT INTO core_areaatuacao (nome) VALUES ('Prática médica');
INSERT INTO core_areaatuacao (nome) VALUES ('Recrutamento e seleção');
INSERT INTO core_areaatuacao (nome) VALUES ('Recursos humanos');
INSERT INTO core_areaatuacao (nome) VALUES ('Recursos renováveis e meio ambiente');
INSERT INTO core_areaatuacao (nome) VALUES ('Rede sem fio');
INSERT INTO core_areaatuacao (nome) VALUES ('Redes');
INSERT INTO core_areaatuacao (nome) VALUES ('Relações governamentais');
INSERT INTO core_areaatuacao (nome) VALUES ('Relações internacionais');
INSERT INTO core_areaatuacao (nome) VALUES ('Relações públicas e comunicações');
INSERT INTO core_areaatuacao (nome) VALUES ('Resolução alternativa de litígios');
INSERT INTO core_areaatuacao (nome) VALUES ('Restaurantes');
INSERT INTO core_areaatuacao (nome) VALUES ('Roupas e moda');
INSERT INTO core_areaatuacao (nome) VALUES ('Saúde, bem-estar e educação física');
INSERT INTO core_areaatuacao (nome) VALUES ('Segurança de redes e computadores');
INSERT INTO core_areaatuacao (nome) VALUES ('Segurança e investigações');
INSERT INTO core_areaatuacao (nome) VALUES ('Segurança pública');
INSERT INTO core_areaatuacao (nome) VALUES ('Seguros');
INSERT INTO core_areaatuacao (nome) VALUES ('Semicondutores');
INSERT INTO core_areaatuacao (nome) VALUES ('Serviços ambientais');
INSERT INTO core_areaatuacao (nome) VALUES ('Serviços da informação');
INSERT INTO core_areaatuacao (nome) VALUES ('Serviços financeiros');
INSERT INTO core_areaatuacao (nome) VALUES ('Serviços individuais e familiares');
INSERT INTO core_areaatuacao (nome) VALUES ('Serviços jurídicos');
INSERT INTO core_areaatuacao (nome) VALUES ('Serviços para eventos');
INSERT INTO core_areaatuacao (nome) VALUES ('Serviços públicos');
INSERT INTO core_areaatuacao (nome) VALUES ('Software');
INSERT INTO core_areaatuacao (nome) VALUES ('Supermercados');
INSERT INTO core_areaatuacao (nome) VALUES ('Suprimentos e equipamentos comerciais');
INSERT INTO core_areaatuacao (nome) VALUES ('Tabaco');
INSERT INTO core_areaatuacao (nome) VALUES ('Tecnologia da informação e serviços');
INSERT INTO core_areaatuacao (nome) VALUES ('Telecomunicações');
INSERT INTO core_areaatuacao (nome) VALUES ('Terceirização e offshoring');
INSERT INTO core_areaatuacao (nome) VALUES ('Tradução e localização');
INSERT INTO core_areaatuacao (nome) VALUES ('Transporte marítimo');
INSERT INTO core_areaatuacao (nome) VALUES ('Transporte/Caminhões/Trens');
INSERT INTO core_areaatuacao (nome) VALUES ('Treinamento e orientação profissional');
INSERT INTO core_areaatuacao (nome) VALUES ('Varejo');
INSERT INTO core_areaatuacao (nome) VALUES ('Veterinária');
INSERT INTO core_areaatuacao (nome) VALUES ('Vidro, cerâmica e concreto');
INSERT INTO core_areaatuacao (nome) VALUES ('Vinhos e destilados');

INSERT INTO core_maturidadeacademica (nome) VALUES ('Básica');
INSERT INTO core_maturidadeacademica (nome) VALUES ('Intermediária');
INSERT INTO core_maturidadeacademica (nome) VALUES ('Superior');
INSERT INTO core_maturidadeacademica (nome) VALUES ('Especializada');
INSERT INTO core_maturidadeacademica (nome) VALUES ('Referência');

INSERT INTO core_maturidadeprofissional (nome) VALUES ('Júnior');
INSERT INTO core_maturidadeprofissional (nome) VALUES ('Pleno');
INSERT INTO core_maturidadeprofissional (nome) VALUES ('Sênior');

INSERT INTO core_cultura (nome) VALUES ('Não flexível');
INSERT INTO core_cultura (nome) VALUES ('Flexível');
INSERT INTO core_cultura (nome) VALUES ('Extremamente flexível');

INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('Agência M3',2,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('Aivis Sistema',1,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('Alterdata',2,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('Data Hex',2,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('DTO',3,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('Falco Sistemas',1,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('Full Screen',2,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('Headthink',1,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('Linx Sistemas e consultoria',3,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('MP Design',3,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('Oasis',3,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('Prion Soluções em Sistemas',2,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('Prisma Sistemas',2,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('RG Sistemas',2,134);
INSERT INTO core_startup (nome, cultura_id, area_id) VALUES ('Wx3',3,134);